source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'kankan' do
    pod 'Alamofire'
    pod 'Kingfisher', '~> 2.0'
    pod 'SnapKit', '~> 0.15.0'
    pod 'MJRefresh'
    pod 'Masonry'
end
